#!/bin/bash

s_code=$(tmux ls | grep code | cut -c 1)
s_wk=$(tmux ls | grep wk | cut -c 1)
s_personal=$(tmux ls | grep personal | cut -c 1)

if [[ -z ${s_code} ]]
then
    tmux new-session -d -s code
fi
if [[ -z ${s_wk} ]]
then
    tmux new-session -d -s wk
fi
if [[ -z ${s_personal} ]]
then
    tmux new-session -d -s personal
fi

