#!/bin/bash

s_code=$(tmux ls | grep cd | cut -c 1)
s_wk=$(tmux ls | grep wk | cut -c 1)
s_personal=$(tmux ls | grep prs | cut -c 1)

if [[ -z ${s_code} ]]
then
    tmux new-session -d -s cd
fi
if [[ -z ${s_wk} ]]
then
    tmux new-session -d -s wk
fi
if [[ -z ${s_personal} ]]
then
    tmux new-session -d -s prs
fi

