#!/bin/bash

s_vim=$(tmux ls | grep vim | cut -c 1)
s_wk=$(tmux ls | grep wk | cut -c 1)
s_personal=$(tmux ls | grep personal | cut -c 1)

if [[ -z ${s_vim} ]]
then
    tmux new-session -d -s vim
fi
if [[ -z ${s_wk} ]]
then
    tmux new-session -d -s wk
fi
if [[ -z ${s_personal} ]]
then
    tmux new-session -d -s personal
fi

