#!/bin/zsh
# LICENSE: PUBLIC DOMAIN
# switch between my layouts
#
# check if no caps options is set; if not, set it
kbOptions=$(setxkbmap -query | awk '/option/{print $2}')
if [ -z "$kbOptions" ]; then
  # setxkbmap -option 'ctrl:nocaps,shift:both_capslock,lv3:ralt_switch,terminate:ctrl_alt_bkspc'
  setxkbmap -option 'shift:both_capslock,lv3:ralt_switch,terminate:ctrl_alt_bkspc'
fi

if [[ -n "$1" ]]; then
  setxkbmap $1
else
  layout=$(setxkbmap -query | awk '/variant/{print $2}')
  case $layout in
    dvp)
      setxkbmap -layout us
      ;;
    *)
      setxkbmap -layout us -variant 'dvp'
      ;;
  esac
fi
